#!/usr/bin/env node
'use strict';
// const { spawn } = require('child_process');
const readline = require('readline');

/*
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function lsExample() {
  const { stdout, stderr } = await exec('nodemon serve');
  console.log('stdout:', stdout);
  console.log('stderr:', stderr);
}
lsExample();
*/

/*
const { execFile } = require('child_process');
const child = execFile('node', ['--version'], (error, stdout, stderr) => {
  if (error) {
    throw error;
  }
  console.log(stdout);
});
*/


// nodemon server & cd app/zaideih && ng serve
// nodemon server && cd app/zaideih && ng serve
// node development
// npm test

// TODO: reading auguments for which app,
// NOTE: node development --angular=zaideih, node production


// const nodemon = spawn('nodemon',['serve']);
// nodemon.stdout.on('data', data => {
//   console.log(data.toString().replace(/[\n\r]/g, ""));
//   const angular = exec('ng serve', {cwd: 'app/zaideih',async:true});
//   angular.stdout.on('data', function(data) {
//     console.log(data.toString().replace(/[\n\r]/g, ""));
//   });
// });
// nodemon.stderr.on('data', data => {
//   console.log(`...${data}`);
// });
// nodemon.on('close', code => {
//   console.log(`Bye bye: ${code}`);
// });


// readline.createInterface({
//   input: nodemon.stdout,
//   output: nodemon.stderr,
//   terminal: false
// }).on('line', function(line) {
//   const angular = exec('ng serve', {cwd: 'app/zaideih',async:true});
//   readline.createInterface({
//     input: angular.stdout,
//     output: angular.stderr,
//     terminal: false
//   }).on('line', function(line) {
//     console.log(line);
//   });
//   console.log(line);
// });


// readline.createInterface({
//   input: nodemon.stdout,
//   terminal: false
// }).on('line', function(line) {
//   console.log(line);
// });


// var async = require('async');
// var exec = require('child_process').exec;
// // nodemon main.js & cd app/zaideih && node test.js
// // nodemon ./bin/host & cd app/zaideih && ng serve
// function execSync() {
//     async.series([
//       execFn('nodemon ./bin/host'),
//       execFn('cd app/zaideih && ng serve')
//     ]);
// }
// var execFn = function(cmd, dir) {
//     return function(cb) {
//         console.log('EXECUTING: '+cmd);
//         exec(cmd, {
//             // cwd: dir
//         }, function(error, stdout, stderr) {
//           console.log(stdout);
//           console.log(error);
//           console.log(stderr);
//             cb();
//         });
//     }
// }
// execSync();


// "startsss": "echo 'asdf'",
// "test": "cd ./app/zaideih & ng",
// "startss": "node ./bin/host",
// "nodemonss": "nodemon ./bin/host",
// "angularss": "cd app/angular && ng serve",
// "zaideih": "nodemon ./bin/host & cd app/zaideih && ng serve",
// "testssss": "nodemon main.js & cd app/zaideih && node test.js"